/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.frontend;

import com.mycompany.backend.trainer.TrainerRole;
import java.io.IOException;

/**
 *
 * @author habib
 */
public class TrainerRoleWindow extends javax.swing.JFrame {
    TrainerRole trainerRole;
    MainMenu mainMenu;

    /**
     * Creates new form TrainerRoleWindow
     * @throws java.io.IOException
     */
//    public TrainerRoleWindow(TrainerRole trainerRole, AdminRole adminRole) throws IOException {
    public TrainerRoleWindow(MainMenu mainMenu) throws IOException {
        this.trainerRole = new TrainerRole();
        this.mainMenu = mainMenu;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMember = new javax.swing.JButton();
        viewMembers = new javax.swing.JButton();
        addClass = new javax.swing.JButton();
        viewClasses = new javax.swing.JButton();
        registerMember = new javax.swing.JButton();
        cancelRegistration = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        viewRegistrations = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addMember.setText("Add Member");
        addMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberActionPerformed(evt);
            }
        });

        viewMembers.setText("View Members");
        viewMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMembersActionPerformed(evt);
            }
        });

        addClass.setText("Add Class");
        addClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassActionPerformed(evt);
            }
        });

        viewClasses.setText("View Classes");
        viewClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewClassesActionPerformed(evt);
            }
        });

        registerMember.setText("Register Member For Class");
        registerMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerMemberActionPerformed(evt);
            }
        });

        cancelRegistration.setText("Cancel Registration");
        cancelRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelRegistrationActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        viewRegistrations.setText("View Registrations");
        viewRegistrations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRegistrationsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registerMember, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(viewClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewRegistrations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(addMember)
                .addGap(18, 18, 18)
                .addComponent(viewMembers)
                .addGap(18, 18, 18)
                .addComponent(addClass)
                .addGap(18, 18, 18)
                .addComponent(viewClasses)
                .addGap(18, 18, 18)
                .addComponent(registerMember)
                .addGap(18, 18, 18)
                .addComponent(cancelRegistration)
                .addGap(18, 18, 18)
                .addComponent(viewRegistrations)
                .addGap(18, 18, 18)
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassActionPerformed
        // TODO add your handling code here:
        AddClass addClass = new AddClass(trainerRole);
        addClass.setVisible(true);
    }//GEN-LAST:event_addClassActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        try {
            trainerRole.logout();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        finally{
            dispose();
            mainMenu.setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void cancelRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelRegistrationActionPerformed
        // TODO add your handling code here:
        CancelRegistration cancelRegistration = new CancelRegistration(trainerRole);
        cancelRegistration.setVisible(true);
    }//GEN-LAST:event_cancelRegistrationActionPerformed

    private void registerMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerMemberActionPerformed
        // TODO add your handling code here:
        RegisterMember registerMember = new RegisterMember(trainerRole);
        registerMember.setVisible(true);
    }//GEN-LAST:event_registerMemberActionPerformed

    private void viewClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewClassesActionPerformed
        // TODO add your handling code here:
        ViewClasses viewClasses = new ViewClasses(trainerRole);
        viewClasses.setVisible(true);
    }//GEN-LAST:event_viewClassesActionPerformed

    private void viewMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMembersActionPerformed
        // TODO add your handling code here:
        ViewMembers viewMembers = new ViewMembers(trainerRole);
        viewMembers.setVisible(true);
    }//GEN-LAST:event_viewMembersActionPerformed

    private void addMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberActionPerformed
        // TODO add your handling code here:
        AddMember addMember = new AddMember(trainerRole);
        addMember.setVisible(true);
        
    }//GEN-LAST:event_addMemberActionPerformed

    private void viewRegistrationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRegistrationsActionPerformed
        // TODO add your handling code here:
        ViewRegistrations viewRegistrations = new ViewRegistrations(trainerRole);
        viewRegistrations.setVisible(true);
    }//GEN-LAST:event_viewRegistrationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClass;
    private javax.swing.JButton addMember;
    private javax.swing.JButton cancelRegistration;
    private javax.swing.JButton logout;
    private javax.swing.JButton registerMember;
    private javax.swing.JButton viewClasses;
    private javax.swing.JButton viewMembers;
    private javax.swing.JButton viewRegistrations;
    // End of variables declaration//GEN-END:variables
}
